AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - features/**/*

Lint/Void:
  Exclude:
    - 'spec/**/*'

Layout/EndAlignment:
  Exclude:
    - features/support/cookbook_helpers.rb
    - features/step_definitions/cookbook_steps.rb
